apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: t8p9oi5pp-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/t8p9oi5pp-dotnet-basic-gitops